Update destroy.yml

diff --git a/.github/workflows/destroy.yml b/.github/workflows/destroy.yml
--- a/.github/workflows/destroy.yml
+++ b/.github/workflows/destroy.yml
@@ -8,9 +8,11 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      # Paso 1: Checkout del repositorio
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      # Paso 2: Configuración de credenciales de AWS
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
@@ -19,13 +21,13 @@ jobs:
           aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
           aws-region: "us-east-1"
 
-      # Descargar el archivo terraform_state desde S3, asegurándonos de que la ruta sea correcta
+      # Paso 3: Descargar el archivo terraform_state desde S3
       - name: Download Terraform State from S3
         run: |
           echo "Downloading terraform_state from S3..."
-          aws s3 cp s3://artefacto-tf/terraform_state.tfstate ./conexion_VPC/terraform_state.tfstate || { echo "Failed to download terraform_state.tfstate from S3"; exit 1; }
+          aws s3 cp s3://artefacto-ftp/terraform_state.tfstate ./conexion_VPC/terraform_state.tfstate || { echo "Failed to download terraform_state.tfstate from S3"; exit 1; }
 
-      # Verificar si el archivo terraform_state.tfstate ha sido descargado correctamente
+      # Paso 4: Verificar que el archivo terraform_state.tfstate se haya descargado correctamente
       - name: Verify Terraform State File Download
         run: |
           if [ ! -f ./conexion_VPC/terraform_state.tfstate ]; then
@@ -33,23 +35,24 @@ jobs:
             exit 1
           fi
 
+      # Paso 5: Instalar Terraform
       - name: Install Terraform
         uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: 1.5.0
 
-      # Inicializar Terraform en el directorio correcto
+      # Paso 6: Inicializar Terraform
       - name: Initialize Terraform
         run: terraform init
         working-directory: ./conexion_VPC
 
-      # Ejecutar Terraform Destroy para destruir los recursos
+      # Paso 7: Ejecutar Terraform Destroy
       - name: Run Terraform Destroy
         run: terraform destroy -auto-approve
         working-directory: ./conexion_VPC
 
-      # Eliminar el archivo terraform_state desde S3 (si es necesario)
+      # Paso 8: Eliminar el archivo terraform_state desde S3 (si es necesario)
       - name: Delete Terraform State File from S3
         run: |
           echo "Deleting terraform_state from S3..."
-          aws s3 rm s3://artefacto-tf/terraform_state.tfstate || { echo "Failed to delete terraform_state.tfstate from S3"; exit 1; }
+          aws s3 rm s3://artefacto-ftp/terraform_state.tfstate || { echo "Failed to delete terraform_state.tfstate from S3"; exit 1; }
