Update destroy.yml

diff --git a/.github/workflows/destroy.yml b/.github/workflows/destroy.yml
--- a/.github/workflows/destroy.yml
+++ b/.github/workflows/destroy.yml
@@ -21,49 +21,37 @@ jobs:
           aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
           aws-region: "us-east-1"
 
-      # Paso 3: Instalar Terraform
-      - name: Install Terraform
-        uses: hashicorp/setup-terraform@v3
-        with:
-          terraform_version: 1.5.0
-
-      # Paso 4: Comprobar si el archivo terraform_state.tfstate existe en S3
-      - name: Check if terraform_state.tfstate exists in S3
-        run: |
-          echo "Checking if terraform_state.tfstate exists in S3..."
-          aws s3 ls s3://artefacto-ftp/terraform_state.tfstate || echo "terraform_state.tfstate not found in S3"
-        
-      # Paso 5: Descargar el archivo terraform_state desde S3
+      # Paso 3: Descargar el archivo terraform_state desde S3
       - name: Download Terraform State from S3
         run: |
           echo "Downloading terraform_state from S3..."
-          aws s3 cp s3://artefacto-ftp/terraform_state.tfstate ./conexion_VPC/terraform_state.tfstate
-          if [ $? -ne 0 ]; then
-            echo "Failed to download terraform_state.tfstate from S3"
-            exit 1
-          fi
+          aws s3 cp s3://artefacto-ftp/terraform_state.tfstate ./conexion_VPC/terraform_state.tfstate || { echo "Failed to download terraform_state.tfstate from S3"; exit 1; }
 
-      # Paso 6: Verificar que el archivo terraform_state.tfstate se haya descargado correctamente
+      # Paso 4: Verificar que el archivo terraform_state.tfstate se haya descargado correctamente
       - name: Verify Terraform State File Download
         run: |
           if [ ! -f ./conexion_VPC/terraform_state.tfstate ]; then
             echo "Terraform state file not found!"
             exit 1
-          else
-            echo "Terraform state file downloaded successfully"
           fi
 
-      # Paso 7: Inicializar Terraform
+      # Paso 5: Instalar Terraform
+      - name: Install Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_version: 1.5.0
+
+      # Paso 6: Inicializar Terraform
       - name: Initialize Terraform
         run: terraform init
         working-directory: ./conexion_VPC
 
-      # Paso 8: Ejecutar Terraform Destroy
+      # Paso 7: Ejecutar Terraform Destroy
       - name: Run Terraform Destroy
         run: terraform destroy -auto-approve
         working-directory: ./conexion_VPC
 
-      # Paso 9: Eliminar el archivo terraform_state desde S3 (si es necesario)
+      # Paso 8: Eliminar el archivo terraform_state desde S3 (si es necesario)
       - name: Delete Terraform State File from S3
         run: |
           echo "Deleting terraform_state from S3..."
