Update destroy.yml

diff --git a/.github/workflows/destroy.yml b/.github/workflows/destroy.yml
--- a/.github/workflows/destroy.yml
+++ b/.github/workflows/destroy.yml
@@ -8,11 +8,9 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      # Paso 1: Checkout del repositorio
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      # Paso 2: Configuración de credenciales de AWS
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
@@ -21,29 +19,28 @@ jobs:
           aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
           aws-region: "us-east-1"
 
-      # Paso 3: Instalar Terraform
+      - name: Download Terraform State from S3
+        run: |
+          aws s3 cp s3://artefacto-ftp/terraform_state.tfstate ./terraform.tfstate
+
+      - name: Verify Terraform State File Exists
+        run: |
+          if [ ! -f terraform.tfstate ]; then
+            echo "Terraform state file not found!"
+            exit 1
+          fi
+
       - name: Install Terraform
         uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: 1.5.0
 
-      # Paso 4: Inicializar Terraform (que configurará el backend remoto)
       - name: Initialize Terraform
         run: terraform init
-        working-directory: ./conexion_VPC
 
-      # Paso 5: Verificar el estado de los recursos
-      - name: Terraform Refresh
-        run: terraform refresh
-        working-directory: ./conexion_VPC
-
-      # Paso 6: Ejecutar Terraform Destroy
       - name: Run Terraform Destroy
         run: terraform destroy -auto-approve
-        working-directory: ./conexion_VPC
 
-      # Paso 7: Eliminar el archivo terraform_state desde S3 (si es necesario)
       - name: Delete Terraform State File from S3
         run: |
-          echo "Deleting terraform_state from S3..."
-          aws s3 rm s3://artefacto-ftp/terraform_state.tfstate || { echo "Failed to delete terraform_state.tfstate from S3"; exit 1; }
+          aws s3 rm s3://artefacto-ftp/terraform_state.tfstate
