Update destroy.yml

diff --git a/.github/workflows/destroy.yml b/.github/workflows/destroy.yml
--- a/.github/workflows/destroy.yml
+++ b/.github/workflows/destroy.yml
@@ -1,15 +1,20 @@
-name: terraform destroy
+name: Terraform Destroy Infrastructure
 
 on:
   workflow_dispatch:
 
 jobs:
-  destroy:
+  destroy_infrastructure:
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+
+      - name: Install AWS CLI
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y awscli
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
@@ -19,42 +24,39 @@ jobs:
           aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
           aws-region: "us-east-1"
 
-      - name: Check if terraform_state file exists in S3
+      - name: Download Terraform State from S3
         run: |
-          aws s3 ls s3://artefactos-jorge/terraform_state_${GITHUB_RUN_ID}.tfstate || echo "terraform_state.tfstate not found in S3"
+          mkdir -p ./terraform
+          aws s3 cp s3://artefactos-jorge/terraform_state.tfstate ./terraform/terraform.tfstate
 
-      - name: Download Terraform State from S3 with unique name
+      - name: Verify Terraform State File Exists
         run: |
-          if aws s3 ls s3://artefactos-jorge/terraform_state_${GITHUB_RUN_ID}.tfstate; then
-            echo "terraform_state.tfstate found, downloading..."
-            aws s3 cp s3://artefactos-jorge/terraform_state_${GITHUB_RUN_ID}.tfstate ./ftp_ldap/terraform.tfstate
-          else
-            echo "terraform_state.tfstate not found in S3, aborting."
+          if [ ! -f ./terraform/terraform.tfstate ]; then
+            echo "Terraform state file not found!"
             exit 1
           fi
 
+      - name: Install Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_version: 1.5.0
+
       - name: Initialize Terraform
-        run: terraform init
+        run: terraform init -reconfigure
         working-directory: ./ftp_ldap
+
+      - name: Empty S3 Bucket Before Destroy
+        run: |
+          aws s3 rm s3://acorrod24081 --recursive
+          versions=$(aws s3api list-object-versions --bucket acorrod24081 --query='{Objects: Versions[].{Key:Key,VersionId:VersionId}}')
+          aws s3api delete-objects --bucket artefactos-jorge --delete "$versions" || true
 
       - name: Run Terraform Destroy
         run: |
-          terraform destroy -auto-approve \
-            -var "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
-            -var "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
-            -var "aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" \
-            -var "public_key=${{ secrets.SSH_PUBLIC_KEY }}"
+         terraform destroy -auto-approve \
+          -var "public_key=${{ secrets.SSH_PUBLIC_KEY }}"
         working-directory: ./ftp_ldap
-
-      - name: Verify if Terraform State File Exists on S3
-        run: |
-          aws s3 ls s3://artefactos-jorge/terraform_state_${GITHUB_RUN_ID}.tfstate || echo "File does not exist"
 
       - name: Delete Terraform State File from S3
         run: |
-          echo "Attempting to delete terraform_state.tfstate from S3"
-          aws s3 rm s3://artefactos-jorge/terraform_state_${GITHUB_RUN_ID}.tfstate || echo "Error deleting file"
-
-      - name: Confirm deletion of Terraform State File from S3
-        run: |
-          aws s3 ls s3://artefactos-jorge/terraform_state_${GITHUB_RUN_ID}.tfstate || echo "File successfully deleted or does not exist"
+          aws s3 rm s3://artefactos-jorge/terraform_state.tfstate || true
