Update destroy.yml

diff --git a/.github/workflows/destroy.yml b/.github/workflows/destroy.yml
--- a/.github/workflows/destroy.yml
+++ b/.github/workflows/destroy.yml
@@ -1,4 +1,5 @@
 name: Terraform Destroy 
+
 on:
   workflow_dispatch:
 
@@ -7,56 +8,53 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      
-name: Checkout repository
-      uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-      
-name: Install AWS CLI
-      run: |
-        sudo apt-get update
-        sudo apt-get install -y awscli
+      - name: Install AWS CLI
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y awscli
 
-      
-name: Configure AWS Credentials
-      uses: aws-actions/configure-aws-credentials@v4
-      with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
-        aws-region: "us-east-1"
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
+          aws-region: "us-east-1"
 
-      
-name: Download Terraform State from S3
-      run: |
-        mkdir -p ./terraform
-        aws s3 cp s3://artefactos-jorge/terraform_state.tfstate ./terraform.tfstate
+      - name: Download Terraform State from S3
+        run: |
+          mkdir -p ./terraform
+          aws s3 cp s3://artefactos-jorge/terraform_state.tfstate ./terraform/terraform.tfstate
 
-      
-name: Verify Terraform State File Exists
-      run: |
-        if [ ! -f ./terraform/terraform.tfstate ]; then
-          echo "Terraform state file not found!"
-          exit 1
-        fi
+      - name: Verify Terraform State File Exists
+        run: |
+          if [ ! -f ./terraform/terraform.tfstate ]; then
+            echo "Terraform state file not found!"
+            exit 1
+          fi
 
-      
-name: Install Terraform
-      uses: hashicorp/setup-terraform@v3
-      with:
-        terraform_version: 1.5.0
+      - name: Install Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_version: 1.5.0
 
-      
-name: Initialize Terraform
-      run: terraform init -reconfigure
-      working-directory: ./ftp_ldap
-      
-name: Run Terraform Destroy
-      run: |
-       terraform destroy -auto-approve \-var "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \-var "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \-var "aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" \-var "public_key=${{ secrets.SSH_PUBLIC_KEY }}"
-      working-directory: ./ftp_ldap
+      - name: Initialize Terraform
+        run: terraform init -reconfigure
+        working-directory: ./ftp_ldap
 
-      
-name: Delete Terraform State File from S3
-      run: |
-        aws s3 rm s3://artefactos-jorge/terraform_state.tfstate || true
+
+      - name: Run Terraform Destroy
+        run: |
+         terraform destroy -auto-approve \
+          -var "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
+          -var "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
+          -var "aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" \
+          -var "public_key=${{ secrets.SSH_PUBLIC_KEY }}"
+        working-directory: ./ftp_ldap
+
+      - name: Delete Terraform State File from S3
+        run: |
+          aws s3 rm s3://artefactos-jorge/terraform_state.tfstate || true
