Update destroy.yml

diff --git a/.github/workflows/destroy.yml b/.github/workflows/destroy.yml
--- a/.github/workflows/destroy.yml
+++ b/.github/workflows/destroy.yml
@@ -35,5 +35,15 @@ jobs:
             -var "public_key=${{ secrets.SSH_PUBLIC_KEY }}"
         working-directory: ./ftp_ldap
 
+      - name: Verify if Terraform State File Exists on S3
+        run: |
+          aws s3 ls s3://artefactos-jorge/terraform_state.tfstate || echo "File does not exist"
+        
       - name: Delete Terraform State File from S3
-        run: aws s3 rm s3://artefactos-jorge/terraform_state.tfstate
+        run: |
+          echo "Attempting to delete terraform_state.tfstate from S3"
+          aws s3 rm s3://artefactos-jorge/terraform_state.tfstate || echo "Error deleting file"
+        
+      - name: Confirm deletion of Terraform State File from S3
+        run: |
+          aws s3 ls s3://artefactos-jorge/terraform_state.tfstate || echo "File successfully deleted or does not exist"
